version: '3.6'
services:
  pypfopt:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder

  jupyter:
    build:
      context: .
      dockerfile: ./binder/Dockerfile
    volumes:
      - ./cookbook:${WORK}
    ports:
      - ${PORT}:8888